config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles, only: [:index]
  resources :searches, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  pg_search_scope :search_by_title,
                  against: :name,
                  using: {
                    tsearch: { prefix: true, any_word: true },
                    trigram: {
                      only: [:name],
                      threshold: 0.25
                    }
                  }

  validates :name, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  validates :query, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  # before_action :authenticate_user!

  def index
    query = params[:query]

    if query.present?
      @articles = Article.search_by_title(query)

      create_search(query, current_user.id)
    else
      @articles = Article.all
    end
  end

  private

  def create_search(query, _user_id)
    return unless query.present? && query.length >= 3

    last_unconfirmed_search = Search.where(user_id: current_user.id, confirmed: false).last

    last_unconfirmed_search.update(confirmed: true) if last_unconfirmed_search && params[:confirmed].present?

    if last_unconfirmed_search && similar_strings?(query, last_unconfirmed_search.query)
      last_unconfirmed_search.update(query: query)
    else
      Search.create(query: query, user_id: current_user.id)
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @user_searches = Search.where(user: current_user).group(:query).order(count: :desc).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def similar_strings?(string_a, string_b, threshold = 0.863)
    JaroWinkler.distance(string_a, string_b, ignore_case: true) >= threshold
  end
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p class="text-lg leading-loose">
    <%= link_to article.name, articles_path(article), class: "text-orange-600 underline hover:text-orange-700" %>
  </p>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <%= render articles %>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="font-bold text-3xl mb-3">Artilces</h1>

<%= form_with(url: articles_path, method: :get, data: {controller: "search-form", turbo_frame: "articles", turbo_action: "advance"}) do |form| %>

  <%= form.label :query, "Search by article name:", class: "block mb-2" %>
  <div class="flex space-x-3">
    <%= form.text_field :query, class: "py-3 px-4 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none", id: "query",  data: {action: "input->search-form#search"} %>
     <%= form.hidden_field :confirmed, 
        id: "confirmed-input", 
        value: nil 
      %>

    <%= form.submit 'Search', class: "px-4 py-3 font-medium
  bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
  </div>
<% end %>

<div class="my-16">
<%= render "articles", articles: @articles %>
</div>
<br>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchRealTime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container mx-auto my-16 lg:px-10 px-4">
  <%= link_to "Back To Articles", root_path, class: "px-4 py-3 font-medium
  inline-block p-6 bg-gradient-to-bl from-green-400 to-blue-400 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
  <%= link_to "Check Analytics Here", searches_path, class: "px-4 py-3 font-medium
  inline-block p-6 bg-gradient-to-bl from-green-400 to-blue-400 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/searches/_search.html.erb
<div>
<h2 class="bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100">
    <%= search[:title] %>
  </h2>
  <p class="bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100">
    <%= "Occurrences: #{search[:count]}" %>
  </p>
</div>

app/views/searches/index.html.erb
<section>
  <header>
    <h1>
      <%= pluralize(@user_searches.length, 'Search') %>
    </h1>
  </header>

  <div >
    <ul>
      <% if @user_searches.empty? %>
        <p>
          &mdash;&nbsp; No searches &nbsp;&mdash;
        </p>
      <% else %>
        <% @user_searches.entries.each do |title, count| %>
          <li>
            <%= render "search", search: {title: title, count: count} %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</section>